# Generated by Django 3.0.4 on 2020-03-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('memory_count', models.IntegerField(default=0)),
                ('need_review_nums', models.IntegerField(default=10)),
                ('now_review_nums', models.IntegerField(default=10)),
                ('share_id', models.CharField(max_length=32)),
                ('share_password', models.CharField(max_length=32)),
                ('copy_id', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='AdminsToDeck', to='Login.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
                ('staffs', models.ManyToManyField(related_name='StaffsToDeck', to='Login.User')),
            ],
        ),
    ]
