# Generated by Django 2.2.7 on 2020-03-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='AdminsToDeck', to='Login.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
                ('staffs', models.ManyToManyField(related_name='StaffsToDeck', to='Login.User')),
            ],
        ),
    ]
