# Generated by Django 2.2.7 on 2020-03-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deck', '0003_auto_20200317_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='copy_id',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='share_id',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='share_password',
        ),
        migrations.AlterField(
            model_name='deck',
            name='need_review_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ShareInfo',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_code', models.CharField(max_length=32, unique=True)),
                ('share_password', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deck.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='CopyInfo',
            fields=[
                ('copy_id', models.AutoField(primary_key=True, serialize=False)),
                ('copy_code', models.CharField(max_length=32, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deck.Deck')),
            ],
        ),
    ]
