# Generated by Django 3.0.4 on 2020-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deck', '0004_auto_20200324_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyinfo',
            name='c_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shareinfo',
            name='c_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
