# Generated by Django 3.0.4 on 2020-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deck', '0005_auto_20200326_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
