# Generated by Django 3.0.4 on 2020-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deck', '0006_deck_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='need_review_nums',
            new_name='today_learn_nums',
        ),
        migrations.AddField(
            model_name='deckinfo',
            name='need_review_nums',
            field=models.IntegerField(default=0),
        ),
    ]
