# Generated by Django 3.0.4 on 2020-04-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deck', '0007_auto_20200402_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckinfo',
            name='single_number',
            field=models.IntegerField(default=20),
        ),
    ]
