# Generated by Django 3.0.4 on 2020-03-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_auto_20200316_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDecks',
            fields=[
                ('public_id', models.AutoField(primary_key=True, serialize=False)),
                ('deck_id', models.IntegerField()),
                ('star_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
                ('star_users', models.ManyToManyField(related_name='UserToStarDeck', to='Login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('public_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.PublicDecks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
