# Generated by Django 3.0.4 on 2020-04-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_auto_20200316_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('deck_id', models.IntegerField()),
                ('people_num', models.IntegerField(default=2)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatToFromUser', to='Login.User')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyGroup.StudyGroup')),
            ],
        ),
    ]
