# Generated by Django 3.0.4 on 2020-04-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200316_1756'),
        ('StudyGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('task_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('review_nums', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyGroup.StudyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_importance', models.BooleanField(default=False)),
                ('is_accomplish', models.BooleanField(default=False)),
                ('is_read_delete', models.BooleanField(default=False)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyGroup.TaskList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
